var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/book/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0uwhjit._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_01fmcp9.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xwe1h1._.js")
R.c("server/chunks/ssr/node_modules_12c9afg._.js")
R.c("server/chunks/ssr/src_app_layout_tsx_0fhx__n._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/src_0v~lkw2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_0vt4uq1._.js")
R.c("server/chunks/ssr/src_app_(public)_051fbv2._.js")
R.c("server/chunks/ssr/src_app_(public)_book_09~se2v._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(public)_book_page_actions_10qsq9u.js")
R.m(12531)
module.exports=R.m(12531).exports
