// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/admin/bookings" | "/admin/bookings/[id]" | "/admin/clients" | "/admin/clients/[id]" | "/admin/inquiries" | "/admin/login" | "/admin/products" | "/admin/settings" | "/book" | "/book/confirmation" | "/book/consult" | "/book/date" | "/book/deposit" | "/book/details" | "/book/time" | "/boulder" | "/collective" | "/contact" | "/faq" | "/gallery" | "/longmont" | "/services" | "/services/[slug]" | "/shop"
type AppRouteHandlerRoutes = "/api/admin/consultations" | "/api/admin/notes" | "/api/admin/rentals" | "/api/consult" | "/api/notify/ashley-alert" | "/api/notify/booking-confirmed" | "/api/notify/reminder" | "/api/notify/weekly-digest" | "/api/rentals"
type PageRoutes = never
type LayoutRoutes = "/" | "/book" | "/book/consult" | "/collective" | "/contact" | "/services"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/admin/bookings": {}
  "/admin/bookings/[id]": { "id": string; }
  "/admin/clients": {}
  "/admin/clients/[id]": { "id": string; }
  "/admin/inquiries": {}
  "/admin/login": {}
  "/admin/products": {}
  "/admin/settings": {}
  "/api/admin/consultations": {}
  "/api/admin/notes": {}
  "/api/admin/rentals": {}
  "/api/consult": {}
  "/api/notify/ashley-alert": {}
  "/api/notify/booking-confirmed": {}
  "/api/notify/reminder": {}
  "/api/notify/weekly-digest": {}
  "/api/rentals": {}
  "/book": {}
  "/book/confirmation": {}
  "/book/consult": {}
  "/book/date": {}
  "/book/deposit": {}
  "/book/details": {}
  "/book/time": {}
  "/boulder": {}
  "/collective": {}
  "/contact": {}
  "/faq": {}
  "/gallery": {}
  "/longmont": {}
  "/services": {}
  "/services/[slug]": { "slug": string; }
  "/shop": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/book": never
  "/book/consult": never
  "/collective": never
  "/contact": never
  "/services": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
